apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  mongo-user: bW9uZ291c2VyCg== #encoded in base 64. Terminal command: echo mongouser | base64
  mongo-password: bW9uZ29wc3dkCg== #encoded in base 64. Terminal command : echo mongopswd | base64
